# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'AYGenericTableNodeController' do

pod 'Texture', :git => 'https://github.com/ay8s/Texture.git', :branch => 'feature/v10'

end
